<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitSettings
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\Settings\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Settings\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'OCA\\Settings\\AppInfo\\Application' => __DIR__ . '/..' . '/../lib/AppInfo/Application.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitSettings::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitSettings::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitSettings::$classMap;

        }, null, ClassLoader::class);
    }
}
